<style>
    .update-img-wrapper {
            display: inline-block;
            text-align: center;
        }
    .update-img-wrapper .btn
        {
            display: block;
        }
</style>
<div class="page-title-wrapper">
    <div class="breadcrumbs">
        <ul class="items">
            <li class="item home">
                <a href="<?php echo htmlspecialchars($block->getBaseUrl()); ?>" title="Go to Home Page">Home</a>
            </li>

            <li class="item create-trails">
                <strong>Update trails</strong>
            </li>
        </ul>
    </div>




    <?php foreach($block->getTrails() as $post){?>






    <div class="content-heading">
        <h2 class="title">Update Trail</h2>
    </div>
</div>
<form class="trail-register-form" action="<?php echo htmlspecialchars($this->getUrl().'trails/post/update/id/'.$post->getId()); ?>" method="post" enctype="multipart/form-data">
    
     <?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey'); 
?>
<input name="form_key" type="hidden" value="<?php echo $FormKey->getFormKey();?>">

    <fieldset class="fieldset">
        <div class="field row">

            <div class="col-sm-8">
            </div>
            <div class="col-sm-4 register-btn-wrap">

                <div style="text-align:right;">
                    <input type="submit" name="submit" class="action primary" value="publish">
                </div>
                <div style="text-align:right;">
                    <input type="reset" name="submit" class="action primary" value="Discard" style="background:#ccc; border-color:#ccc;" >
                </div>
            </div>

        </div>
        <div class="row field">
            <div class="col-sm-12">
                <label class="label" for="trails_name"><span>Trails Name</span></label>
                <div class="control">
                    <input type="text" name="trails_name" value="<?php echo htmlspecialchars($post->getTrailsName()); ?>" placeholder="Trails Name" required>
                </div>
            </div>
        </div>
        <div class="row field">
            <div class="col-sm-4">
                <div class="field">
                    <label class="label" for="trails_start_date"><span>Start Date</span></label>
                    <div class="control date-block">
<!--                        --><?php // $trailsDate=strtotime($post->getTrailsStartDate()); ?>
<!---->
<!--                        --><?php //echo date('dd/mm/yyyy',$trailsDate); ?>


                        <input type="date" name="trails_start_date" placeholder="Start Date"  value="<?php echo htmlspecialchars($post->getTrailsStartDate()); ?>" required>
                        <label class="input-group-addon btn" for="testdate">
                            <span class="fa fa-calendar"></span>
                        </label>
                    </div>
                </div>

            </div>
            <div class="col-sm-4">
                <div class="field">
                    <label class="label" for="trails_end_date"><span>End Date</span></label>
                    <div class="control date-block">
                        <input type="date" name="trails_end_date" placeholder="End Date" value="<?php echo htmlspecialchars($post->getTrailsEndDate()); ?>" required>
                        <label class="input-group-addon btn" for="testdate">
                            <span class="fa fa-calendar"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="field">
                    <label class="label" for="trails_vehicle_name"><span>Vehicle Name</span></label>
                    <div class="control">
                        <input type="text" name="trails_vehicle_name" placeholder="Vehicle Name" value="<?php echo htmlspecialchars($post->getTrailsVehicleName()); ?>" required>
                    </div>
                </div>
            </div>

        </div>
        <div class="row field">
            <div class="col-sm-4">
                <div class="field">
                    <label class="label" for="trails_trip_duration"><span>Duration</span></label>
                    <div class="control">
                        <input type="text" name="trails_trip_duration" placeholder="Duration" value="<?php echo htmlspecialchars($post->getTrailsTripDuration()); ?>" required>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="field">
                    <label class="label" for="trails_start_point"><span>Start Point</span></label>
                    <div class="control">
                        <input type="text" name="trails_start_point" placeholder="Start Point" value="<?php echo htmlspecialchars($post->getTrailsStartPoint()); ?>" required>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="field">
                    <label class="label" for="trails_end_point"><span>End Point</span></label>
                    <div class="control">
                        <input type="text" name="trails_end_point" placeholder="End Point" value="<?php echo htmlspecialchars($post->getTrailsEndPoint()); ?>" required>
                    </div>
                </div>
            </div>
        </div>
        <div class="field row">
            <div class="col-sm-12">
                <div class="field">
                    <label class="label" for="trails_describing"><span>Description</span></label>
                    <div class="control">
                        <textarea name="trails_describing" rows="10" placeholder="Start describing your trail here..." required  id="short_description"><?php echo $post->getTrailsDescribing(); ?> </textarea>

                    </div>
                </div>
            </div>

        </div>




        <div class="field row">
            <div class="col-sm-12 upload-wrapper">
                <label class="label"><span>upload images & videos</span></label>
                <div class="uploader">
                    <label class="label" for="trails_url"><span>+add photos/videos</span></label>
                    <input type="file" name="trails_url[]" placeholder="Image" multiple="multiple" id="gallery-photo-add">
                    
                     <input type="hidden" id="trails_url_old" name="trails_url_old" value=""> 
                </div>
                <div id="erroediv" style="color:red;"></div>
                <div class="gallery">


                    <?php $image=explode(',',$post->getTrailsUrl()) ;  ?>

                    <?php $images= array_splice($image,0); $i=0; foreach ($images  as $img) { $i=$i+1; ?>
                    <div class="update-img-wrapper">
                     <img src="<?php echo htmlspecialchars($block->getBaseUrl()); ?>pub/media/trails/<?php echo htmlspecialchars($img); ?>">
                     <span style="cursor:pointer;" class="delete-gallery-btn" data-id="<?php echo htmlspecialchars($img); ?>">delete</span>
                    </div>
                    <?php  } ?>
                    
                </div>
            </div>
        </div>


    </fieldset>
</form>
<?php  }?>

<script>

    require([ 'jquery', 'jquery/ui'], function($){ 
   

    jQuery(function() {
    // Multiple images preview in browser
     function addToDeleteBucket(name) {
         var bucket = $('#trails_url_old');
         var entries = bucket.val().split(',');
         entries.push(name);
         bucket.val(entries);
     }
     
     $('.delete-gallery-btn').click(function(e) {
         var imgName = $(this).data("id");
         addToDeleteBucket(imgName);
         $(this).parents('.update-img-wrapper').remove();
     });
    
    var imagesPreview = function(input, placeToInsertImagePreview) {

        if (input.files) {
            var fileSize = 0;
            var maxSize = 10*1024*1024;
            var files = input.files;
            var filesAmount = input.files.length;
            $("#erroediv").text("");
            for (var i = 0; i < filesAmount; i++) {
                fileSize += files[i].size;
            }

            if (fileSize >= maxSize) {
                input.value = "";
                
                $("#erroediv").text("Total Image size should be less than 8 MB");
                
            

            } else {
                for (i = 0; i < filesAmount; i++) {
                    var reader = new FileReader();
                    reader.onload = function (event) {
                        var block = '<div class="update-img-wrapper">';
                        block += '<img src="'+ event.target.result +'"/>';
                        block += '</div>';
                        jQuery(block).appendTo(placeToInsertImagePreview);
                    }
                    reader.readAsDataURL(input.files[i]);
                }
            }
        }

    };

    jQuery('#gallery-photo-add').on('change', function() {
        imagesPreview(this, 'div.gallery');
    });

});
});
</script>


<script>
    require(['jquery','tiny_mce/tiny_mce_src'], function($){
        $( document ).ready(function(){
            tinyMCE.init({
                mode : "exact",
                elements: "short_description", // id of textarea
                theme : "advanced",
                plugins: "paste",
                // paste_text_sticky : true,
                // ....................
     
                // .................
                
                
                theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect",
                theme_advanced_buttons2 : "",
                theme_advanced_buttons3 : "",
                theme_advanced_buttons4 : "",
                theme_advanced_toolbar_location : "top",
                theme_advanced_toolbar_align : "left",
                // theme_advanced_path_location : "bottom",
                extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
                theme_advanced_resize_horizontal : 'true',
                theme_advanced_resizing : 'true',
                apply_source_formatting : 'true',
                convert_urls : 'false',
                force_br_newlines : 'true',
                doctype : '',
                setup : function(ed) {
                    ed.onChange.add(function(ed, evt) {
                        $('#history_comment').text(tinyMCE.activeEditor.getContent());
                    });
                    // ed.onInit.add(function(ed) {
                    //  ed.pasteAsPlainText = true;
                    //  });
                    // ed.onPaste.add( function(ed, e, o) {
                    //   ed.execCommand('mcePasteText', true);
                    //     return tinymce.dom.Event.cancel(e);
                    //     });    
                    
                    
                    
                }
            }); // close tinyMCE

        }); // close jquery ready
    }); // close require
    

</script>

<script language="javascript" type="text/javascript" src="<?php echo htmlspecialchars($block->getBaseUrl()); ?>static/adminhtml/Magento/backend/en_US/tiny_mce/tiny_mce.js"></script>

